### ISSUE TITLE
Does not handle strings with escaped quotes

### ISSUE THREAD

**Issue by AlexCharlton** [rgovind92/partial-json-parser#2]
For example, trying to parse the valid (complete) JSON string
```
> partialParse('{"my_json_value":"{\\"a\\": 1}"}')
```
will throw an `Error: Invalid token`

While `JSON.parse` will succeed:
```
> JSON.parse('{"my_json_value":"{\\"a\\": 1}"}')
{my_json_value: "{"a": 1}"}
```

**Comment by gov-ind** [comment]
Fixed in 1.1.1 by df789e21faf4de078d9066e21fafd91abda64c41
