### ISSUE TITLE
Termination is not guaranteed

### ISSUE THREAD

**Issue by jlfwong** [rgovind92/partial-json-parser#3]
Hi! Thanks for writing this, a PR adding support for partial JSON import into speedscope was opened with this repository: https://github.com/jlfwong/speedscope/pull/202, but I had to revert the PR because `partial-json-parser` doesn't guarantee termination.

Reproduction:

```
> require('partial-json-parser/package.json').version
'1.1.1'
> var partialParse = require('partial-json-parser');
undefined
> partialParse('`')
```

At this point the code hangs.

**Comment by gov-ind** [comment]
Sorry for the late response - This fixed in 1.2.2.

I've also removed babel to a devDependency (as it should have been).
